name: Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: unit
            args: -skip Integration
          - name: integration
            args: -run Integration -v
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go test ./pkg/chzzk/... ${{ matrix.args }}
