name: Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go test ./pkg/chzzk/... -skip Integration

  integration:
    name: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go test ./pkg/chzzk/... -run Integration -v
